check: boot-check

boot-check: skiboot.lid
	./test/run_boot_test.sh

OP_BUILD_BOOT_CHECK=op-build-v1.0 op-build-v1.1 op-build-v1.2 op-build-v1.2.1

boot-check-%: skiboot.lid skiboot.map
	SKIBOOT_MEM_DUMP=skiboot-$(@:boot-check-%=%).dump SKIBOOT_ZIMAGE=`pwd`/opal-ci/images/$(@:boot-check-%=%)/zImage.epapr ./test/run_boot_test.sh

boot-tests: boot-check $(OP_BUILD_BOOT_CHECK:%=boot-check-%)

boot-coverage-report: boot-tests extract-gcov skiboot.map all-boot-hardware
	CROSS=$(CROSS) BOOT_TESTS="hello_world boot_test ${OP_BUILD_BOOT_CHECK} ${FSP_GCOV_MACHINES}" ./test/make-boot-coverage-report.sh

boot-hardware-%: skiboot.lid skiboot.map
	./external/boot-tests/boot_test.sh -v -p -t $(@:boot-hardware-%=%) -1 skiboot.lid
	./external/boot-tests/extract_gcov.sh $(@:boot-hardware-%=%)

all-boot-hardware: $(FSP_GCOV_MACHINES:%=boot-hardware-%)