# -*-Makefile-*-
TEST_FLAGS = -D__TEST__

LIBFLASH_TEST := libflash/test/test-flash libflash/test/test-ecc libflash/test/test-blocklevel libflash/test/test-mbox

LCOV_EXCLUDE += $(LIBFLASH_TEST:%=%.c)

.PHONY : libflash-check libc-coverage
libflash-check: $(LIBFLASH_TEST:%=%-check) $(CORE_TEST:%=%-gcov-run)
libflash-coverage: $(LIBFLASH_TEST:%=%-gcov-run)

check: libflash-check libc-coverage
coverage: libflash-coverage

strict-check: TEST_FLAGS += -D__STRICT_TEST__
strict-check: check

$(LIBFLASH_TEST:%=%-gcov-run) : %-run: %
	$(call QTEST, TEST-COVERAGE ,$< , $<)

$(LIBFLASH_TEST:%=%-check) : %-check: %
	$(call QTEST, RUN-TEST ,$(VALGRIND) $<, $<)

LIBFLASH_TEST_EXTRA :=  libflash/test/stubs.o libflash/test/mbox-server.o
$(LIBFLASH_TEST_EXTRA) : %.o : %.c
	$(call Q, HOSTCC ,$(HOSTCC) $(HOSTCFLAGS) $(TEST_FLAGS) -Wno-suggest-attribute=const -g -c -o $@ $<, $<)

$(LIBFLASH_TEST) : libflash/libflash.c libflash/ecc.c libflash/blocklevel.c $(LIBFLASH_TEST_EXTRA)
$(LIBFLASH_TEST) : % : %.c
	$(call Q, HOSTCC ,$(HOSTCC) $(HOSTCFLAGS) $(TEST_FLAGS) -Wno-suggest-attribute=const -O0 -g -I include -I . -o $@ $< $(LIBFLASH_TEST_EXTRA), $<)

$(LIBFLASH_TEST:%=%-gcov): %-gcov : %.c %
	$(call Q, HOSTCC ,$(HOSTCC) $(HOSTCFLAGS) $(HOSTGCOVCFLAGS) -I include -I . -o $@ $< libflash/test/stubs.o, $<)

-include $(wildcard libflash/test/*.d)

clean: libflash-test-clean

libflash-test-clean:
	$(RM) libflash/test/*.o $(LIBFLASH_TEST)
	$(RM) libflash/test/*.d
	$(RM) libflash/test/*-gcov
