# -*-Makefile-*-
LIBFLASH_TEST := libflash/test/test-flash

check: $(LIBFLASH_TEST:%=%-check)

$(LIBFLASH_TEST:%=%-check) : %-check: %
	$(VALGRIND) $<

libflash/test/stubs.o: libflash/test/stubs.c
	$(HOSTCC) $(HOSTCFLAGS) -g -c -o $@ $<

$(LIBFLASH_TEST) : libflash/test/stubs.o libflash/libflash.c

$(LIBFLASH_TEST) : % : %.c 
	$(HOSTCC) $(HOSTCFLAGS) -O0 -g -I include -I . -o $@ $< libflash/test/stubs.o

clean: libflash-test-clean

libflash-test-clean:
	$(RM) libflash/test/*.o $(LIBFLASH_TEST)
