# -*-Makefile-*-
CORE_TEST := core/test/run-device core/test/run-mem_region core/test/run-malloc core/test/run-malloc-speed core/test/run-mem_region_init core/test/run-mem_region_release_unused core/test/run-mem_region_release_unused_noalloc core/test/run-trace core/test/run-msg

CORE_TEST_NOSTUB := core/test/run-console-log-buf-overrun

check: $(CORE_TEST:%=%-check) $(CORE_TEST_NOSTUB:%=%-check)

$(CORE_TEST:%=%-check) : %-check: %
	$(VALGRIND) $<

$(CORE_TEST_NOSTUB:%=%-check) : %-check: %
	$(VALGRIND) $<

core/test/stubs.o: core/test/stubs.c
	$(HOSTCC) $(HOSTCFLAGS) -g -c -o $@ $<

$(CORE_TEST) : core/test/stubs.o

$(CORE_TEST) : % : %.c 
	$(HOSTCC) $(HOSTCFLAGS) -O0 -g -I include -I . -I libfdt -o $@ $< core/test/stubs.o

$(CORE_TEST_NOSTUB): % : %.d

$(CORE_TEST_NOSTUB) : % : %.c 
	$(HOSTCC) $(HOSTCFLAGS) -O0 -g -I include -I . -I libfdt -o $@ $<

$(CORE_TEST_NOSTUB): % : %.d

core/test/stubs.o: core/test/stubs.d

core/test/%.d: core/test/%.c
	$(HOSTCC) $(HOSTCFLAGS) -I include -I . -I libfdt -M $< > $@

-include core/test/*.d

clean: core-test-clean

core-test-clean:
	$(RM) -f core/test/*.[od] $(CORE_TEST)
