# -*-Makefile-*-

check: hdata-check 

# Add some test ntuples for open source version...
hdata-check: hdata/test/hdata_to_dt
#	$(VALGRIND) hdata/test/hdata_to_dt -q hdata/test/spira.bin hdata/test/ntuples.bin

hdata/test/stubs.o: hdata/test/stubs.c
	$(call Q, HOSTCC , $(HOSTCC) $(HOSTCFLAGS) -g -c -o $@ $<, $<)

hdata/test/hdata_to_dt: hdata/test/hdata_to_dt.c hdata/test/stubs.o
	$(call Q, HOSTCC , $(HOSTCC) $(HOSTCFLAGS) -DTEST -O0 -g -I hdata -I include -I . -I libfdt -o $@ $< hdata/test/stubs.o, $<)

-include $(wildcard hdata/test/*.d)

clean: hdata-test-clean

hdata-test-clean:
	$(RM) hdata/test/*.o hdata/test/hdata_to_dt
