# -*-Makefile-*-
LIBC_TEST := libc/test/run-time

check: $(LIBC_TEST:%=%-check)

coverage: $(LIBC_TEST:%=%-gcov-run)

$(LIBC_TEST:%=%-gcov-run) : %-run: %
	$<

$(LIBC_TEST:%=%-check) : %-check: %
	$(VALGRIND) $<

$(LIBC_TEST) : % : %.c
	$(HOSTCC) $(HOSTCFLAGS) -O0 -g -I include -I . -I libfdt -I libc/include -o $@ $<

$(LIBC_TEST:%=%-gcov): %-gcov : %.c %
	$(HOSTCC) $(HOSTCFLAGS) -fprofile-arcs -ftest-coverage -lgcov -O0 -g -I include -I . -I libfdt -I libc/include -o $@ $<

-include $(wildcard libc/test/*.d)

clean: libc-test-clean

libc-test-clean:
	$(RM) -f libc/test/*.[od] $(LIBC_TEST) $(LIBC_TEST:%=%-gcov)
