FROM ubuntu:latest
RUN apt-get update -qq
RUN apt-get install -y gcc-powerpc64le-linux-gnu gcc
RUN apt-get install -y wget xterm
RUN apt-get install -y gcc-arm-linux-gnueabi
RUN wget ftp://public.dhe.ibm.com/software/server/powerfuncsim/p8/packages/v1.0-2/systemsim-p8_1.0-2_amd64.deb
RUN dpkg -i systemsim-p8_1.0-2_amd64.deb
RUN apt-get -y install eatmydata
RUN eatmydata apt-get -y install build-essential gcc python g++ pkg-config libz-dev libglib2.0-dev libpixman-1-dev libfdt-dev git libstdc++6 valgrind
COPY . /build/
WORKDIR /build
ENTRYPOINT ./opal-ci/build-ubuntu-16.04.sh
