FROM centos:6
RUN yum -y update && yum clean all
RUN yum -y install wget xterm gcc git xz
RUN wget https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/4.8.0/x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
RUN mkdir /opt/cross
RUN tar -C /opt/cross -xf x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
COPY . /build/
WORKDIR /build
ENTRYPOINT ./opal-ci/build-centos6.sh
