FROM centos:7
RUN yum -y update && yum clean all
RUN yum -y install wget xterm gcc git xz make diffutils findutils expect valgrind valgrind-devel
RUN wget https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/4.8.0/x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
RUN mkdir /opt/cross
RUN tar -C /opt/cross -xf x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
COPY . /build/
WORKDIR /build
# We don't have a custom centos 7 build, same script for now
ENTRYPOINT ./opal-ci/build-centos6.sh
