FROM fedora:24
RUN dnf -y install wget curl xterm gcc git xz make diffutils findutils expect valgrind valgrind-devel ccache
RUN dnf -y install gcc-powerpc64-linux-gnu 
COPY . /build/
WORKDIR /build
ENTRYPOINT ./opal-ci/build-fedora24.sh
